apiVersion: apps/v1
kind: Deployment
metadata:
  name: hce
  labels:
    app: hce
    project: hce
  namespace: hce
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: hce
      project: hce
  template:
    metadata:
      labels:
        app: hce
        project: hce
    spec:
      containers:
        - name: hce
          image: container_image
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 12Mi
              cpu: 3m
            limits:
              memory: 32Mi
              cpu: 10m
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: hce
  labels:
    project: hce
  namespace: hce
spec:
  type: ClusterIP
  selector:
    app: hce
    project: hce
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
